### ISSUE TITLE
p-value is shrinking as n_perm increases

### ISSUE THREAD

**Issue by skchao74** [kwuthrich/scinference#2]
Thank you for open-sourcing the codes! When I tested the "iid" function in conformal.R on my dataset. I have a total of T01 = 210 with T0 = 182 and T1 = 28, apparently I couldn't have computed all possible permutations as suggested in your paper. The output p-value was getting smaller as I increased n_perm from 1K to 1 million. The output p-value is ranging from 9.99e-04 (n_perm = 1K) to 9.99999e-07 (n_perm = 1 million). On the other hand, with the moving block permutation, I got p-value 0.00952381.
I understand that the "iid" method would lead to a more accurate p-value with a greater n_perm, and the "iid" method is more accurate than the moving block permutation method (as suggested by the paper), so should I expect that my actual p-value is probably even smaller than 10e-7? I would greatly appreciate your inputs!

**Comment by kwuthrich** [comment]
Thanks for your question. Let me address two issues separately:
1) The p-value based on the iid permutations is an approximate p-value since it is often not computationally feasible to compute all permutations. The larger n_perm, the better the approximation (ie the closer the approximate p-value will be to the "true" p-value). Since there will be an approximation error even when you use n_perm = 1mio, it's not possible to say whether the p-value is even smaller than 10e-7. What is known is that the minimal p-value that you can get for a given n_perm is of order 1/n_perm (when the test statistic is the largest among all permutations). 
2) It is difficult to compare the moving block and the iid p-values in practice since these two p-values are valid under different assumptions (iid is valid under iid errors; moving block is valid under weak dependence). 
I hope this helps!

**Comment by skchao74** [comment]
Thank you for your comments! I have two follow-up questions:
(1) I observed that the p-value is decreasing as I increased n_perm from 1K to 1M. Would this decreasing pattern continue to hold as n_perm -> factorial(T01)? If so, I would expect the "actual" p-value to be smaller than that at n_perm =1M.
(2) Since the moving block is robust to weak dependence, it should also be accurate under iid assumption as well. Does it mean the moving block permutation is more robust than the iid permutation, and thus is always recommended to use?

**Comment by kwuthrich** [comment]
1) Not necessarily but it's possible, depending on the true p-value. The p-value need not be monotonic in n_perm.
2) I would always recommend using moving block permutations if you have enough time periods -- they are more robust. The disadvantage of moving block permutations is that you only have few elements in the group of permutations. For example, if you have 9 periods, you would never reject at the 10% level since the smallest p-value is 1/9.

**Comment by skchao74** [comment]
Thanks for the prompt feedback. I have no more questions and I'll close this issue.
